// Generated by CoffeeScript 2.5.1
(function() {
  var User, user;

  User = Backbone.Model.extend({
    initialize: function() {
      return console.log('hello');
    }
  });

  user = new User();

}).call(this);
