// Generated by CoffeeScript 2.5.1
(function() {
  var AppView, User, UserView, el, user;

  User = Backbone.Model.extend({
    defaults: function() {
      return {
        name: 'Max',
        phone: '123'
      };
    },
    initialize: function() {
      if (!this.get('name') && !this.get('phone')) {
        this.set({
          'name': this.defaults.name
        });
        return this.set({
          'phone': this.defaults.phone
        });
      }
    },
    clear: function() {
      return this.destroy();
    }
  });

  UserView = Backbone.View.extend({
    events: {
      'click': 'isClicked'
    },
    isClicked: function() {
      return console.log(this);
    },
    render: function() {
      console.log(this);
      return this.$el.html('Hello');
    }
  });

  el = document.getElementById('app');

  user = new UserView({
    el: el
  });

  user.render();

  AppView = Backbone.View.extend({
    el: document.getElementById('app'),
    events: {
      'click': 'addUser'
    },
    initialize: function() {},
    addUser: function(e) {
      e.preventDefault();
      return console.log('clicked');
    }
  });

}).call(this);
